### ISSUE TITLE
No module named `annotated_types`

### ISSUE THREAD

**Issue by john-b-yang** [LiveCodeBench/LiveCodeBench#22]
Hi LiveCodeBench team, thanks for the great contribution and work!

I'd like to run evaluation on a custom set of generations (not created using the `evaluation` mechanism in this repository.

This is what I have done:
* Created conda environment, then `pip install poetry; poetry install` to install dependencies
* Ran `python -m lcb_runner.runner.custom_evaluator --custom_output_file preds_lcb.json`

`preds_lcb.json` is the custom file I've created. It is a list of dictionaries that looks like the following:
```json
{
    "question_id": "1873_A",
    "code_list": [
        """def main(input):
    <code implementation here>
    return abc
        """
    ]
}
```

I am running into this problem when I run the custom_evaluator script. It seems like the error is related to pydantic. Perhaps the wrong version was installed?

I am running this on a Macbook air with an M2 chip.

```
% python -m lcb_runner.runner.custom_evaluator --custom_output_file preds_lcb.json
Traceback (most recent call last):
  File "/opt/miniconda3/envs/lcb/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/lcb/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/johnbyang/Documents/Research/third-party/LiveCodeBench/lcb_runner/runner/custom_evaluator.py", line 5, in <module>
    from lcb_runner.runner.scenario_router import (
  File "/Users/johnbyang/Documents/Research/third-party/LiveCodeBench/lcb_runner/runner/scenario_router.py", line 11, in <module>
    from lcb_runner.prompts import (
  File "/Users/johnbyang/Documents/Research/third-party/LiveCodeBench/lcb_runner/prompts/__init__.py", line 3, in <module>
    from lcb_runner.prompts.test_output_prediction import format_prompt_test_output
  File "/Users/johnbyang/Documents/Research/third-party/LiveCodeBench/lcb_runner/prompts/test_output_prediction.py", line 3, in <module>
    from anthropic import HUMAN_PROMPT, AI_PROMPT
  File "/opt/miniconda3/envs/lcb/lib/python3.10/site-packages/anthropic/__init__.py", line 3, in <module>
    from . import types
  File "/opt/miniconda3/envs/lcb/lib/python3.10/site-packages/anthropic/types/__init__.py", line 5, in <module>
    from .usage import Usage as Usage
  File "/opt/miniconda3/envs/lcb/lib/python3.10/site-packages/anthropic/types/usage.py", line 3, in <module>
    from .._models import BaseModel
  File "/opt/miniconda3/envs/lcb/lib/python3.10/site-packages/anthropic/_models.py", line 23, in <module>
    from pydantic.fields import FieldInfo
  File "/opt/miniconda3/envs/lcb/lib/python3.10/site-packages/pydantic/fields.py", line 14, in <module>
    import annotated_types
ModuleNotFoundError: No module named 'annotated_types'
```

**Comment by john-b-yang** [comment]
Ah! It ended up being some minor issues (1 or 2 missing libraries). I will suggest a PR that I think might help within the next two weeks. Thanks for all the offline help! 🙏🏼

**Comment by Naman-ntc** [comment]
I was able to reproduce this. `poetry add annotated_types` fixes the issue. Thanks for the report!
