### ISSUE TITLE
code_generation_lite loading is broken when split is not defined

### ISSUE THREAD

**Issue by alat-rights** [LiveCodeBench/LiveCodeBench#32]
```
>>> lcb_codegen = load_dataset("livecodebench/code_generation_lite", version_tag="release_v2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "load.py", line 2587, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File builder.py", line 1244, in as_dataset
    datasets = map_nested(
               ^^^^^^^^^^^
  File "py_utils.py", line 477, in map_nested
    mapped = [
             ^
  File "py_utils.py", line 478, in <listcomp>
    _single_map_nested((function, obj, types, None, True, None))
  File "py_utils.py", line 370, in _single_map_nested
    return function(data_struct)
           ^^^^^^^^^^^^^^^^^^^^^
  File "builder.py", line 1274, in _build_single_dataset
    ds = self._as_dataset(
         ^^^^^^^^^^^^^^^^^
  File "builder.py", line 1348, in _as_dataset
    dataset_kwargs = ArrowReader(cache_dir, self.info).read(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "arrow_reader.py", line 254, in read
    raise ValueError(msg)
ValueError: Instruction "train" corresponds to no data!
```

**Comment by rShar01** [comment]
I guess the intended usage is to only have the "test" split data for generation? Would be useful to have a note in the documentation on hugging face!

**Comment by Naman-ntc** [comment]
Thanks for the report. Solved.
