### ISSUE TITLE
Getting error when running the PT models 

### ISSUE THREAD

**Issue by Vattikondadheeraj** [LiveCodeBench/LiveCodeBench#50]
Hey,

I am trying to run the llama-3-8B and llama-3.1-8B PT models but I am getting the following errors. I have attached my inference command below. Let me know if I am missing something

`python -m lcb_runner.runner.main --model meta-llama/Meta-Llama-3.1-8B  --scenario testoutputprediction --evaluate`

This is the error 

```
(VllmWorkerProcess pid=26526) INFO 11-05 21:12:02 model_runner.py:1067] Loading model weights took 7.5122 GB
INFO 11-05 21:12:02 model_runner.py:1067] Loading model weights took 7.5122 GB
INFO 11-05 21:12:03 distributed_gpu_executor.py:57] # GPU blocks: 62177, # CPU blocks: 4096
INFO 11-05 21:12:03 distributed_gpu_executor.py:61] Maximum concurrency for 4096 tokens per request: 242.88x
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/toolkit/.conda/envs/myenv/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/home/toolkit/.conda/envs/myenv/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/toolkit/scratch/LLMcode/Evaluate/LiveCodeBench/lcb_runner/runner/main.py", line 213, in <module>
[rank0]:     main()
[rank0]:   File "/home/toolkit/scratch/LLMcode/Evaluate/LiveCodeBench/lcb_runner/runner/main.py", line 66, in main
[rank0]:     results: list[list[str]] = runner.run_main(remaining_benchmark, format_prompt)
[rank0]:   File "/home/toolkit/scratch/LLMcode/Evaluate/LiveCodeBench/lcb_runner/runner/base_runner.py", line 177, in run_main
[rank0]:     prompts = [
[rank0]:   File "/home/toolkit/scratch/LLMcode/Evaluate/LiveCodeBench/lcb_runner/runner/base_runner.py", line 178, in <listcomp>
[rank0]:     format_prompt(problem, self.model.model_style) for problem in benchmark
[rank0]:   File "/home/toolkit/scratch/LLMcode/Evaluate/LiveCodeBench/lcb_runner/prompts/test_output_prediction.py", line 309, in format_prompt_test_output
[rank0]:     raise NotImplementedError(
[rank0]: NotImplementedError: LanguageModelStyle LMStyle.GenericBase not implemented
[rank0]:[W1105 21:12:11.542098998 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
/home/toolkit/.conda/envs/myenv/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by Naman-ntc** [comment]
We do not support base models for test output prediction task due to formatting issues. Please use instruct models
