### ISSUE TITLE
Installation error with python 3.11

### ISSUE THREAD

**Issue by ivankrylatskoe** [LiveCodeBench/LiveCodeBench#53]
Hello. 
I get the following installation error. 
This happens because `pyext` doesn't support python 3.11.
Please, do not use `pyext`. It was released more than 10 years ago and it is not supported now.

```Collecting pyext==0.7
  Using cached pyext-0.7.tar.gz (7.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ixffrhk0/pyext_98a264c7046e48a394d727075cb9fbba/setup.py", line 6, in <module>
          import pyext
        File "/tmp/pip-install-ixffrhk0/pyext_98a264c7046e48a394d727075cb9fbba/pyext.py", line 117, in <module>
          oargspec = inspect.getargspec
                     ^^^^^^^^^^^^^^^^^^
      AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

**Comment by Naman-ntc** [comment]
Hi, thanks we are aware of this and are planning to release a cleaner version of the autograder soon!
